In [ ]:
#!pip install numpy
import numpy as np

In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [32]:
import numpy as np
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``o

In [33]:
import numpy as np

#print("arr variable is type:", type(arr))
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
import numpy as np

print(np.arange(1,6,2))
print(np.arange(3, 57, 4))

[1 3 5]
[ 3  7 11 15 19 23 27 31 35 39 43 47 51 55]


In [35]:

np.arange(0, 100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `end

In [ ]:
np.linspace(0, 10, num=100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [45]:
import making_library



In [ ]:
making_library.add_sum(5,6)

11

In [53]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
type(arr)

[ 1  2  3  4  5  6  7  8  9 10]


numpy.ndarray

In [54]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Incremint by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [58]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [59]:
height = np.array([172, 159, 175, 180, 167, 173])

In [61]:
print(height[0:3])

[172 159 175]


In [62]:
np.sort(height)

array([159, 167, 172, 173, 175, 180])

In [63]:
np.mean(height)

np.float64(171.0)

In [64]:
np.median(height)

np.float64(172.5)

In [65]:
np.average(height)

np.float64(171.0)

In [67]:
np.histogram(height)

(array([1, 0, 0, 1, 0, 0, 2, 1, 0, 1]),
 array([159. , 161.1, 163.2, 165.3, 167.4, 169.5, 171.6, 173.7, 175.8,
        177.9, 180. ]))

In [75]:
a = height[height > 175]
b = height[height < 170]

print(f"height > 175 = {a}")
print(f"height < 170 = {b}")

height > 175 = [180]
height < 170 = [159 167]


In [77]:
print(height[(height > 170) & (height < 178)])
print(height[(height < 167) | (height > 178)])

[172 175 173]
[159 180]


In [78]:
c = np.array([[1, 2, 3], [4, 5, 6]])

In [82]:
print(c)

c.ndim

[[1 2 3]
 [4 5 6]]


2

In [80]:
# 3-D array with 2-D arrays as its elements
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [99]:
print(d.ndim)
print(d.shape)

print(d[0])

print(d[0][1][2])

np.array(d)


3
(2, 2, 3)
[[1 2 3]
 [4 5 6]]
6


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])