### Numpy exercise

1. Import the numpy package as np.

In [28]:
import numpy as np

2. Create a numpy array with the first 10 values of the Fibonacci sequence. Then reverse the order of this array.

In [29]:
# Create a numpy array with the first 10 Fibonacci numbers
fibonacci_array = np.array([1, 1, 2, 3, 5, 8, 13, 21, 34, 55])  # Fibonacci sequence

# Reverse the order of the array using slicing
reversed_fibonacci = fibonacci_array[::-1]

# Display the reversed array
print("Reversed Fibonacci array:", reversed_fibonacci)

Reversed Fibonacci array: [55 34 21 13  8  5  3  2  1  1]


3. Create another array with 10 random integers between 1 and 40.

In [30]:
import random
random_array = [random.randint(1, 40) for _ in range(10)]
print(random_array)
# Example output: [15, 32, 7, 24, 39, 12, 28, 3, 36, 19]

[7, 17, 27, 22, 27, 1, 31, 40, 9, 29]


4. Find the sum of the random array.

In [31]:
ans = sum(random_array)
print (ans)

210


5. Add the array of 10 random integers to the reversed array of the Fibonacci sequence element wise.

In [32]:
new_array = random_array + reversed_fibonacci
print(new_array)

[62 51 48 35 35  6 34 42 10 30]


6. Create a 2D array that is a 3x3 matrix.

In [33]:
array_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2D)
print(array_2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


7. Pick out the first value in the second row. Change its value to be 2 more than the old value.

In [34]:
# Create a 2D array (3 rows, 4 columns)
array_2d = [
    [10, 20, 30, 40],
    [15, 25, 35, 45],  # Second row
    [12, 22, 32, 42]
]

print("Original array:")
for row in array_2d:
    print(row)

# Pick out the first value in the second row and increase it by 2
old_value = array_2d[1][0]  # Row 1 (second row), Column 0 (first value)
array_2d[1][0] = old_value + 2

print("\nAfter modification:")
for row in array_2d:
    print(row)

print(f"\nOld value: {old_value}")
print(f"New value: {array_2d[1][0]}")

Original array:
[10, 20, 30, 40]
[15, 25, 35, 45]
[12, 22, 32, 42]

After modification:
[10, 20, 30, 40]
[17, 25, 35, 45]
[12, 22, 32, 42]

Old value: 15
New value: 17


8. Pick out the first and third columns of the 3x3 matrix.

In [35]:
import numpy as np

# First, let's create a sample 3x3 matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Original 3x3 matrix:")
print(matrix)

# 8. Pick out the first and third columns
first_third_columns = matrix[:, [0, 2]]
print("\n8. First and third columns:")
print(first_third_columns)

Original 3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

8. First and third columns:
[[1 3]
 [4 6]
 [7 9]]


9. Use np.hstack to add another column to the array.

In [36]:
# 9. Use np.hstack to add another column
new_column = np.array([[10], [11], [12]])  # New column to add
matrix_with_new_col = np.hstack([matrix, new_column])
print("\n9. Matrix with new column added:")
print(matrix_with_new_col)


9. Matrix with new column added:
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


10. Find the sum of each column in the array.

In [37]:
# 10. Find the sum of each column
column_sums = np.sum(matrix_with_new_col, axis=0)
print("\n10. Sum of each column:")
print(column_sums)


10. Sum of each column:
[12 15 18 33]


11. Multiply row 2 in the array by row 4 element wise.

In [38]:
# For questions 11-14, let's create a larger 4x4 array
array_4x4 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
print("\nNew 4x4 array:")
print(array_4x4)

# 11. Multiply row 2 by row 4 element-wise
# Note: indices start at 0, so row 2 is index 1, row 4 is index 3
row2_times_row4 = array_4x4[1] * array_4x4[3]
print("\n11. Row 2 multiplied by row 4 (element-wise):")
print(row2_times_row4)


New 4x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

11. Row 2 multiplied by row 4 (element-wise):
[ 65  84 105 128]


12. Reverse the order of the rows in the array

In [39]:
# 12. Reverse the order of the rows
reversed_rows = array_4x4[::-1]
print("\n12. Array with reversed row order:")
print(reversed_rows)


12. Array with reversed row order:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


13. Create a copy of your array.

In [40]:
# 13. Create a copy of the array
array_copy = array_4x4.copy()
print("\n13. Copy of the array:")
print(array_copy)


13. Copy of the array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


14. Convert your Numpy array to a list.

In [41]:
# 14. Convert NumPy array to a list
array_as_list = array_4x4.tolist()
print("\n14. Array converted to list:")
print(array_as_list)
print(f"Type: {type(array_as_list)}")


14. Array converted to list:
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
Type: <class 'list'>
